DROP TABLE IF EXISTS avis;
DROP TABLE IF EXISTS acteurs_films;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS roles_utilisateurs;
DROP TABLE IF EXISTS utilisateurs;
DROP TABLE IF EXISTS participants;
DROP TABLE IF EXISTS categories;